project:
  type: website
  output-dir: docs

website:
  title: "CS5805-ML1-Blog"
  repo-url: https://github.com/imkamie/CS5805-ML1-Blog
  repo-actions: [source]

format:
  html:
    code-fold: true
    code-tools: true
    theme:
      light: flatly
      dark: darkly

jupyter: python3

